version: '3'
services:
  mongodb:
    restart: always
    image: "mongo"
    volumes:
      - ./data:/data/db
    ports:
     - "27017:27017"
    networks:
      - app-net
  backend:
    restart: always
    tty: true
    build: 
      context: ./node-backend/
      dockerfile: Dockerfile-prod
    environment:
      NOTES_ENC_KEY: ${NOTES_ENC_KEY}
      NOTES_SIG_KEY: ${NOTES_SIG_KEY}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      NOTES_SECRET: ${NOTES_SECRET}
      VIRTUAL_HOST: api.notes365.ga
    ports:
      - "6200:6200"
    volumes:
      - ./node-backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    networks:
      - app-net
      - default
  frontend:
    container_name: frontend
    restart: always
    tty: true
    build: 
      context: ./react-frontend/
      dockerfile: Dockerfile-prod
    ports:
      - "5010:5010"
    volumes:
      - ./react-frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    environment:
      VIRTUAL_HOST: notes365.ga
      PORT: 5010 
    networks:
      - app-net
      - default
networks:
  default:
    external:
      name: nginx-proxy
  app-net:
    internal: true
