services:
  mongodb:
    restart: always
    image: "mongo"
    volumes:
      - ./data:/data/db
    ports:
     - "27017:27017"
  backend:
    restart: always
    tty: true
    build: ./node-backend/
    ports:
      - "6200:6200"
    volumes:
      - ./node-backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
  frontend:
    restart: always
    tty: true
    build: ./react-frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./react-frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
