version: '2'
services:
  mongodb:
    image: "mongo"
    volumes:
      - ./data:/data/db
    ports:
     - "27017:27017"
  backend:
    build: ./node-backend/
    environment:
      - NOTES_ENC_KEY=${NOTES_ENC_KEY}
      - NOTES_SIG_KEY=${NOTES_SIG_KEY}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    ports:
      - "6200:6200"
    volumes:
      - ./node-backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./react-frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./react-frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
