version: '3'
services:
  mongodb:
    restart: unless-stopped
    image: "mongo:4.4.6"
    volumes:
      - ./data:/data/db
    ports:
     - "27017:27017"
    networks:
      - app-net

  backend:
    restart: unless-stopped
    tty: true
    build:
      context: ./node-backend/
      dockerfile: Dockerfile-prod
    environment:
      NOTES_ENC_KEY: bIU1xFgMmlGqKHlKmnHBf8/mhYLlqkBnKNm3Kz8Grn8=
      NOTES_SIG_KEY: ZSoQ+D9j1QwmOPZAEIGRU5cFjpyfm+XZEM3WbNBRZ0JKFdRQcYwGaj4993a+KME5uiNIngs8vLdRtFEGgcGaDQ==
      EMAIL_USER: notesapp@yahoo.com
      EMAIL_PASSWORD: knauulxreaayjpol
      NOTES_SECRET: ffjJhsFts73g!w3$$ds
      VIRTUAL_HOST: api-notes365.costa365.site
    ports:
      - "6200:6200"
    volumes:
      - ./node-backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    networks:
      - app-net
      - default
  frontend:
    container_name: frontend
    restart: unless-stopped
    tty: true
    build:
      context: ./react-frontend/
      dockerfile: Dockerfile-prod
    ports:
      - "5010:5010"
    volumes:
      - ./react-frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    environment:
      VIRTUAL_HOST: notes365.costa365.site
      PORT: 5010
    networks:
      - app-net
      - default
networks:
  default:
    name: nginx-proxy
    external: true
  app-net:
    internal: true
