version: '3'
services:
  mongodb:
    image: "mongo"
    volumes:
      - ./data:/data/db
    ports:
     - "27017:27017"
    networks:
      - app-net
  backend:
    build: 
      context: ./node-backend/
      dockerfile: Dockerfile-prod
    environment:
      - NOTES_ENC_KEY=${NOTES_ENC_KEY}
      - NOTES_SIG_KEY=${NOTES_SIG_KEY}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - NOTES_SECRET=${NOTES_SECRET}
    ports:
      - "6200:6200"
    volumes:
      - ./node-backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    networks:
      - app-net
      - outside
  frontend:
    container_name: frontend
    build: 
      context: ./react-frontend/
      dockerfile: Dockerfile-prod
    ports:
      - "5000:5000"
    volumes:
      - ./react-frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - app-net
  notes-letsencrypt:
    image: linuxserver/letsencrypt
    container_name: notes-letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/letsencrypt:/config
    environment:
      - EMAIL=${EMAIL_PASSWORD}
      - URL=notes365.tk
      - VALIDATION=http
      - TZ=Europe/Stockholm
    depends_on:
      - frontend
    networks:
      - app-net
      - outside
networks:
  outside:
    external:
      name: ExternalNetwork
  app-net:
    internal: true
