FROM node:14.21-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY ./ ./

ENV NODE_ENV production
RUN npm config set unsafe-perm true
RUN npm install
RUN npm install --production -g serve

CMD [ "npm", "run-script", "start-prod" ]
